version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/www:/var/www/html
    depends_on:
      - app

  app:
    build: ./php
    env_file: .env
    environment:
      DATABASE_HOST: db
    depends_on:
      - db
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./data/www:/var/www/html

  db:
   image: mariadb
   env_file: .env
   ports:
     - 3306:3306
   restart: always
   volumes:
     - db-data:/var/lib/mysql

volumes:
  db-data:
