version: '3'
services:
  nginx:
    build: ./nginx
    container_name: "qass-nginx"
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - ./data/www:/var/www/qass-news-server/public
    depends_on:
      - app
    networks:
      - qass_net

  app:
    build: ./php
    container_name: "qass-php"
    # env_file: .env
    environment:
      DATABASE_HOST: db
      MYSQL_DATABASE: qass
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    depends_on:
      - db
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      # - ./data/www:/var/www/qass-news-server/public
    networks:
      - qass_net

  db:
    build: ./db
    container_name: "qass-db"
    # env_file: .env
    environment:
      MYSQL_DATABASE: qass
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - db-data:/var/lib/mysql
    networks:
      - qass_net


volumes:
  db-data:

networks:
  qass_net:
    driver: bridge
