version: '3'
services:
  nginx:
    build: ./nginx
    container_name: "qass-nginx"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      qass_app_net:
        ipv4_address: 172.16.238.10
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  app:
    build: ./php
    container_name: "qass-php"
    environment:
      DATABASE_HOST: db
      MYSQL_DATABASE: qass
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    depends_on:
      - db
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      qass_app_net:
        ipv4_address: 172.16.238.11
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  db:
    build: ./db
    container_name: "qass-db"
    environment:
      MYSQL_DATABASE: qass
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    restart: always
    volumes:
      - db-data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      qass_app_net:
        ipv4_address: 172.16.238.12
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  migration:
    build: ./migration
    container_name: "qass-migration"
    depends_on:
      - db
    networks:
      qass_app_net:
        ipv4_address: 172.16.238.13
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  cron:
    build: ./cron
    container_name: "qass-cron"
    depends_on:
      - nginx
    networks:
      qass_app_net:
        ipv4_address: 172.16.238.14
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
        
networks:
  qass_app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/16

volumes:
  db-data:
    driver: local
