version: '3'
services:
  nginx:
    build: ./nginx
    container_name: "laravel-nginx"
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/www:/var/www/html
    depends_on:
      - app

  app:
    build: ./php
    container_name: "laravel-php"
    env_file: .env
    environment:
      DATABASE_HOST: db
    depends_on:
      - db
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./data/www:/var/www/html

  db:
   build: ./db
   container_name: "laravel-db"
   env_file: .env
   ports:
     - 3306:3306
   restart: always
   volumes:
     - db-data:/var/lib/mysql

volumes:
  db-data:
