version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/www:/var/www/html
    depends_on:
      - php

  php:
    build: ./php
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./data/www:/var/www/html

  #mariadb:
  #  image: mariadb
  #  ports:
  #    - 3306:3306
  #  restart: always
  #  environment:
  #    MYSQL_ROOT_PASSWORD: password
